export ACCOUNT_BASE_PATH=/${CLUSTER_NAME}/pcpt/config/k8s-config/accounts/
export ARTIFACT_REPO_URL=s3://${CLUSTER_NAME}-binarybucket
export AWS_PROFILE=csg
export BACKUP_URL=ssm://${CLUSTER_NAME}/pcpt/service/storage/backup/uri
export CLUSTER_BUCKET_NAME=ssm://${CLUSTER_NAME}/pcpt/service/storage/ping-federate-cluster-bucket/name
export CLUSTER_STATE_REPO_URL=ssh://APKA2IO25QZRRRNUAQPP@git-codecommit.us-west-2.amazonaws.com/v1/repos/${CLUSTER_NAME}-cluster-state-repo
#export ENVIRONMENT=
export IRSA_BASE_PATH=/${CLUSTER_NAME}/pcpt/irsa-role/
export IS_BELUGA_ENV=true
export IS_GA=false
export IS_MULTI_CLUSTER=false
export K8S_CONTEXT=${CLUSTER_NAME}
export K8S_GIT_URL=https://github.com/pingidentity/ping-cloud-base
export LEGACY_LOGGING=false
export PD_MONITOR_BUCKET_URL=ssm://${CLUSTER_NAME}/pcpt/service/storage/pd-monitor/uri
export LOG_ARCHIVE_URL=ssm:/${CLUSTER_NAME}/pcpt/service/storage/logs/uri
export LOG_SYNC_SECONDS=10
export MYSQL_DATABASE=pingcentral_${CLUSTER_NAME}
export MYSQL_USER=ssm://aws/reference/secretsmanager//pcpt/ping-central/dbserver#username
export MYSQL_PASSWORD=ssm://aws/reference/secretsmanager//pcpt/ping-central/dbserver#password
export MYSQL_SERVICE_HOST=beluga-${CLUSTER_NAME}-mysql.cmpxy5bpieb9.us-west-2.rds.amazonaws.com
#export NEW_RELIC_LICENSE_KEY=
#export ORCH_API_SSM_PATH_PREFIX=
export PING_ARTIFACT_REPO_URL=https://ping-artifacts.s3-us-west-2.amazonaws.com
#export PLATFORM_EVENT_QUEUE_NAME=
export PRIMARY_REGION=us-west-2
export PRIMARY_TENANT_DOMAIN=${CLUSTER_NAME}.ping-oasis.com
export REGION=us-west-2
#export REGION_NICK_NAME=
#export REGISTRY_NAME=
export SECONDARY_TENANT_DOMAIN=
export SERVER_PROFILE_URL=ssh://APKA2IO25QZRRRNUAQPP@git-codecommit.us-west-2.amazonaws.com/v1/repos/${CLUSTER_NAME}-profile-repo
export SERVICE_SSM_PATH_PREFIX=/${CLUSTER_NAME}/pcpt/service
export SIZE=x-small
export TARGET_DIR=/tmp/sandbox
export TENANT_DOMAIN=${CLUSTER_NAME}.ping-oasis.com
export TENANT_NAME=${CLUSTER_NAME}
export PF_PROVISIONING_ENABLED=false
export PCB_PATH="${PROJECT_DIR}"

# NOTE: these variables must exactly match those set by your CLUSTER_NAME-cluster.properties file
export CSR_PATH="${HOME}/${CLUSTER_NAME}-cluster-state-repo"
export PR_PATH="${HOME}/${CLUSTER_NAME}-profile-repo"
# export PCB_SSH_KEY_PATH="${HOME}/.ssh/YOUR_GITHUB_SSH_KEY"
export CSR_SSH_KEY_PATH="${HOME}/.ssh/gitlab-user"
export PR_SSH_KEY_PATH="${HOME}/.ssh/gitlab-user"
export SSH_ID_KEY_FILE="${HOME}/.ssh/gitlab-user"
export SSH_ID_PUB_FILE="${HOME}/.ssh/gitlab-user.pub"
export ENV_VARS="${CI_SCRIPTS_DIR}/k8s/deploy/ci-cd-cluster.properties"
