#Cloudwatch related values
cloudwatch:
  enabled : ${CLOUDWATCH_ENABLED}
#The IRSA role ARN to be used for the CWAgent serviceAccount, for the customer environment
  irsaCwAgentAnnotationKeyValue: "${IRSA_CWAGENT_ANNOTATION_KEY_VALUE}"
  image:
    repository: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/amazon/cloudwatch-agent
    tag: 1.300026.3b189

  resources:
    limits:
      cpu:  200m
      memory: 200Mi
    requests:
      cpu: 200m
      memory: 200Mi


#Newrelic related values
global:
  cluster: ${TENANT_NAME}_${ENV}_${REGION}_k8s-cluster
