apiVersion: v1
kind: ServiceAccount
metadata:
  name: ping-serviceaccount

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pingaccess-serviceaccount

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ping-role
rules:
  - apiGroups:
    - "batch"
    resources:
    - "jobs"
    verbs:
    - get
    - create
  - apiGroups:
    - ""
    resources:
    - "configmaps"
    verbs:
    - create
    - get
    - list
    - watch
    - patch
  - apiGroups:
    - ""
    resources:
    - "pods"
    - "pods/log"
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - "secrets"
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
  - apiGroups:
    - ""
    resources:
    - "persistentvolumeclaims"
    verbs:
    - delete
    - get
    - create
  - apiGroups:
    - ""
    - "apps"
    resources:
    - "statefulsets"
    - "deployments"
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - "pods/exec"
    verbs:
    - create
  - apiGroups:
    - networking.k8s.io
    resources:
    - ingresses
    verbs:
    - list
    - watch
    - get
  - apiGroups:
    - ""
    resources:
    - endpoints
    verbs:
    - get

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ping-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ping-role
subjects:
  - kind: ServiceAccount
    name: ping-serviceaccount

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pingaccess-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ping-role
subjects:
  - kind: ServiceAccount
    name: pingaccess-serviceaccount

