apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logstash-elastic-s3
spec:
  template:
    spec:
      containers:
        - name: logstash
          resources:
            # Guaranteed QoS (requests = limits).
            # Ensures dedicated CPU & Mem reservation for Logstash to avoid
            # CPU throttling &noisy-neighbor interference
            limits:
              cpu: "1"
              memory: 6Gi
            requests:
              cpu: "1"
              memory: 6Gi
          env:
            - name: LS_JAVA_OPTS
              # Heap/direct split sized for stable GC and IO buffer headroom.
              value: '-Xms2560m -Xmx2560m -XX:MaxDirectMemorySize=768m'
