kind: Namespace
apiVersion: v1
metadata:
  name: amazon-cloudwatch
---
kind: Namespace
apiVersion: v1
metadata:
  name: newrelic
# ---
# kind: Namespace
# apiVersion: v1
# metadata:
#   name: prometheus
