kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../../base/monitoring/

patchesJson6902:
- path: grafana/grafana-limits.yaml
  target:
    group: grafana.integreatly.org
    version: v1beta1
    kind: Grafana
    name: grafana
- path: prometheus/prometheus-limits.yaml
  target:
    group: apps
    version: v1
    kind: StatefulSet
    name: prometheus

