# p1as-cluster-tools values

# ingress-nginx-public values
ingress-nginx-public:
  ingress-nginx:
    serviceAccount:
      annotations:
        ${IRSA_INGRESS_ANNOTATION_KEY_VALUE}
    controller:
      service:
        annotations:
          ${NLB_NGX_PUBLIC_ANNOTATION_KEY_VALUE}
      # Whole container needs to be defined here due to ingress-nginx helm templating
      # See: https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/templates/controller-deployment.yaml#L180-L181
      extraContainers:
      - name: sigsci-agent
        image: public.ecr.aws/r2h3l6e4/pingcloud-services/sigsci-agent/dev:v2.2-release-branch-latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1500m
            memory: 1Gi
          requests:
            cpu: 1200m
            memory: 500Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: false
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
        env:
          - name: AGENT_NAME
            value: ${TENANT_NAME}-${ENVIRONMENT_TYPE}-${REGION}
          - name: AWS_REGION
            value: ${REGION}
          - name: ENVIRONMENT_PREFIX
            value: ${ENVIRONMENT_PREFIX}
        volumeMounts:
          - mountPath: /var/run/
            name: sigsci-socket

# ingress-nginx-private values
ingress-nginx-private:
  ingress-nginx:
