kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: elastic-stack-logging

configMapGenerator:
- name: logstash-pipeline-customer
  files:
    - 01-input.conf
    - 02-filters.conf
    - 99-outputs.conf