- op: replace
  path: /spec/template/spec/containers/0/resources/limits/cpu
  value: "1500m"
- op: replace
  path: /spec/template/spec/containers/0/resources/limits/memory
  value: "6Gi"
- op: replace
  path: /spec/template/spec/containers/0/resources/requests/cpu
  value: "750m"
- op: replace
  path: /spec/template/spec/containers/0/resources/requests/memory
  value: "3Gi"

