# PingFederate application settings that are shared with both PingFederate Admin and Engine
pingfederate:

  # Application settings that is only for PingFederate Admin
  admin:
    # PingFederate Heap
    pfMinHeap: "3072m"
    pfMaxHeap: "3072m"
    pfMinYgen: "1536m"
    pfMaxYgen: "1536m"

    statefulSet:
      resources:
        limits:
          memory: "4Gi"
          cpu: "2"
        requests:
          memory: "4Gi"
          cpu: "2"

  # Application settings that is only for PingFederate Engine
  engine:
    # PingFederate Heap
    pfMinHeap: "3072m"
    pfMaxHeap: "3072m"
    pfMinYgen: "1536m"
    pfMaxYgen: "1536m"

    statefulSet:
      hpa:
        minReplicas: 3
        maxReplicas: 8

      resources:
        limits:
          memory: "4Gi"
          cpu: "2"
        requests:
          memory: "4Gi"
          cpu: "2"