apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-tls-cert
  namespace: cert-manager
spec:
  secretName: acme-tls-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - '*.ping-demo.com'
  privateKey:
    rotationPolicy: Never
    algorithm: RSA
    encoding: PKCS1
    size: 2048

