apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory

    # Use ISRG Root X1 as the preferred certificate chain as it has better compatibility with all devices/browsers:
    # https://letsencrypt.org/docs/certificate-compatibility/
    # Pre-P1AS 2.0.0 this field was nulled out as there were issues in previous cert-manager versions, which are now
    # fixed in cert-manager 1.15 and later: https://github.com/cert-manager/cert-manager/pull/6755
    preferredChain: 'ISRG Root X1'

    # Email address used for ACME registration
    email: support@pingidentity.com

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod

    # ACME DNS-01 provider configurations
    solvers:
    - dns01:
        route53:
          region: us-west-2
      selector:
        dnsZones:
        - ping-demo.com
