# kind: Service
# apiVersion: v1
# metadata:
#   name: grafana
#   namespace: prometheus
#   labels:
#     app: grafana
# spec:
#   selector:
#     app: grafana
#   ports:
#   - port: 3000
#     name: grafana
#   clusterIP: None
