kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: elastic-stack-logging

resources:
# - alerts
- index-templates
# - ism-policies
- notifications
- security_configs
- bootstrap.yaml
- cluster.yaml
- service.yaml
- storageclass.yaml
- serviceaccount.yaml
- tenants.yaml

openapi:
  path: opensearch-schema.json