kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: elastic-stack-logging

resources:
- notifications
- security_configs
- bootstrap.yaml
- cluster.yaml
- service.yaml
- storageclass.yaml
- serviceaccount.yaml
- tenants.yaml

openapi:
  path: opensearch-schema.json



configMapGenerator:
  - name: os-index-templates
    files:
      - kube-proxy.json
  - name: os-alerts-kube-proxy
    files:
      - err_in_log.json      