apiVersion: v1
kind: ServiceAccount
metadata:
  name: enrichment
  labels:
    app: enrichment

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: enrichment
  labels:
    app: enrichment
rules:
  - apiGroups:
    - ""
    resources:
    - "configmaps"
    verbs:
    - create
    - update
    - get
    - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: enrichment
  labels:
    app: enrichment
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: enrichment
subjects:
  - kind: ServiceAccount
    name: enrichment

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: enrichment
  labels:
    app: enrichment
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "update", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create", "update", "watch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: enrichment
roleRef:
  kind: ClusterRole
  name: enrichment
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: enrichment
