- op: replace
  path: /spec/template/spec/containers/0/resources/limits/cpu
  value: "2000m"
- op: replace
  path: /spec/template/spec/containers/0/resources/limits/memory
  value: "8Gi"
- op: replace
  path: /spec/template/spec/containers/0/resources/requests/cpu
  value: "1000m"
- op: replace
  path: /spec/template/spec/containers/0/resources/requests/memory
  value: "4Gi"

