apiVersion: v1
kind: ConfigMap
metadata:
  name: pingcloud-healthcheck-environment-variables
data:
  PORT: "5000"
  DEBUG_MODE: "1"
  SSL_KEY: "/tls.key"
  SSL_CERT: "/tls.crt"
  WEB_CONCURRENCY: "1"
  PYTHON_MAX_THREADS: "1"