#
# This defines the pingcloud-healthcheck deployment.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingcloud-healthcheck
  labels:
    role: pingcloud-healthcheck
spec:
  selector:
    matchLabels:
      role: pingcloud-healthcheck
  template:
    metadata:
      name: pingcloud-healthcheck
      labels:
        role: pingcloud-healthcheck
    spec:
      serviceAccount: beluga-tools-serviceaccount
      containers:
      - name: pingcloud-healthcheck
        image: {{ .Values.ecrRegistryName }}/healthcheck{{ .Values.ecrEnv }}:{{ .Values.healthcheckImageTag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: pingcloud-healthcheck-environment-variables
        resources:
          limits:
            memory: {{ .Values.healthcheck.deployment.resources.limits.memory }}
            cpu: {{ .Values.healthcheck.deployment.resources.limits.cpu }}
          requests:
            memory: {{ .Values.healthcheck.deployment.resources.requests.memory }}
            cpu: {{ .Values.healthcheck.deployment.resources.requests.cpu }}
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 3          
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 3
        ports:
        - containerPort: 5000
