---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
data:
  stream-snippet: |
    ## Two created backends:
    ## pingdirectory-admin: hostname used to maintain functionality for envs that have x509 authentication enabled for PingDirectory
    ## default: all other traffic to be terminated at nginx.
    map $ssl_preread_server_name $backend {
      "~^pingdirectory-admin\." "pingdirectory.ping-cloud.svc.cluster.local:1636";
      default "127.0.0.1:1636";
    }

    server {
      listen 636;
      ssl_preread on;
      proxy_pass $backend;
    }

    server {
      listen 1636 ssl;
      set $upstream "pingdirectory.ping-cloud.svc.cluster.local:1636";
      proxy_pass $upstream;
      proxy_ssl on;

      ## setting as default for now, adding in dynamically setting cert in PDO-7596
      ssl_certificate /etc/ingress-controller/ssl/ping-cloud-acme-tls-cert.pem;
      ssl_certificate_key /etc/ingress-controller/ssl/ping-cloud-acme-tls-cert.pem;
    }
---