# This defines the ingress for the healthcheck service

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: healthcheck-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx-public
spec:
  tls:
  - hosts:
    - healthcheck.{{ .Values.dnsZone }}
  rules:
  - host: healthcheck.{{ .Values.dnsZone }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: healthcheck
            port:
              number: 5000
