#
# This service exposes the pingcloud-healthcheck port to the cluster.
#
apiVersion: v1
kind: Service
metadata:
  name: healthcheck
  labels:
    role: healthcheck
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    role: pingcloud-healthcheck
