# IRSA role annotation for logstash-elastic service account.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: logstash-elastic
  namespace: elastic-stack-logging
  annotations:
    purpose: service-account-for-logstash-elastic
    ${IRSA_LOGSTASH_ANNOTATION_KEY_VALUE}
