# kind: Kustomization
# apiVersion: kustomize.config.k8s.io/v1beta1

# namespace: elastic-stack-logging

# configMapGenerator:
# - name: logstash-pipeline-main
#   files:
#     - 01-input.conf
#     - 02-input-filters.conf
#     - 03-ingress-filters.conf
#     - 04-pa-filters.conf
#     - 05-pd-filters.conf
#     - 06-pds-filters.conf
#     - 07-pf-filters.conf
#     - 08-pc-filters.conf
#     - 09-pdg-filters.conf
#     - 10-outputs.conf