kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:

# PingCloud common resources and configs. These should always be included. DO NOT comment them out.
- pingcommon
- pingaccess-was/config
- pingaccess-was/ff-external-ingress
- pingaccess/config
- pingdelegator/config
- pingdatasync/config

# The following resource reference includes all ping applications by default. However, it may be tweaked to roll out
# applications independent of one another to enforce proper dependency order. Refer to the docs in kustomization.yaml
# under the granular-updates directory.
- granular-updates

patchesStrategicMerge:

### Ping app known_hosts file ###

- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: known-hosts-config
  data:
    known_hosts: |
      ${KNOWN_HOSTS_CLUSTER_STATE_REPO}

### Ping cloud stack service account ###
- |-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ping-serviceaccount
    annotations:
      purpose: service-account-for-ping-cloud-stack
      ${IRSA_PING_ANNOTATION_KEY_VALUE}

### Ping access service account ###
- |-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: pingaccess-serviceaccount
    annotations:
      purpose: service-account-for-ping-access
      ${IRSA_PA_ANNOTATION_KEY_VALUE}


### P14C Bootstrap service account ###
- |-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: p14c-bootstrap-serviceaccount
    annotations:
      purpose: service-account-for-ping-cloud-stack
      ${IRSA_PING_ANNOTATION_KEY_VALUE}
