kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ping-cloud

commonLabels:
  app: ping-cloud

resources:
- ../cloud-generic
- pingcloud-p14c-bootstrap

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: discovery-service
  files:
  - scripts/get_ssm_env_vars.sh