### This is originally an exact copy of secrets.yaml and left around for future reference. It does NOT contain any
### secrets and safe to leave around.

### Argo CD ###

# Deploy the git key of the CD tool to the cluster state repo
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: argo-git-deploy
  namespace: argocd
data:
  identity: |
    ${SSH_ID_KEY_BASE64}

---

### Ping app SSH private key ###

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ssh-id-key-secret
data:
  id_rsa: |
    ${SSH_ID_KEY_BASE64}

---

#Argocd slack token

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: argocd-notifications-secret
data:
  slack-token: ${ARGOCD_SLACK_TOKEN_BASE64}

---

# NewRelic license key to send APM data
# apiVersion: v1
# kind: Secret
# type: Opaque
# metadata:
#   name: newrelic-license-key
# data:
#   NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY_BASE64}

# ---

# apiVersion: v1
# kind: Secret
# type: Opaque
# metadata:
#   name: newrelic-license-key
#   namespace: newrelic
# data:
#   NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY_BASE64}

---

# In order to change the PingCentral admin password, 2 rollouts are necessary. 
#
# 1. On the 1st rollout, change the PC_ADMIN_USER_PASSWORD as appropriate and the 
#    LAST_UPDATE_REASON for PingCentral. This will cause a rollout/restart of
#    the PingCentral pod.
# 2. On the 2nd rollout, change the OLD_PC_ADMIN_USER_PASSWORD to match the 
#.   PC_ADMIN_USER_PASSWORD. This will cause an update of the secret. 
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingcentral-passwords

---

### Licenses ###

# Add pingcentral.lic (case-sensitive) to the data section with the base64-encoded value of the license file
apiVersion: v1
kind: Secret
metadata:
  name: pingcentral-license
type: Opaque

---

### Product passwords ###

# Supported keys:
# Exported as environment variables: PA_ADMIN_USER_PASSWORD, OLD_PA_ADMIN_USER_PASSWORD,
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingaccess-was-passwords

---

# Add pingaccess.lic (case-sensitive) to the data section with the base64-encoded value of the license file
apiVersion: v1
kind: Secret
metadata:
  name: pingaccess-was-license
type: Opaque

---

# Logstash password to send logs to the opensearch
apiVersion: v1
kind: Secret
metadata:
  name: os-logstash-creds
  namespace: elastic-stack-logging

---

# Customer PingOne application info for external IdP setup
apiVersion: v1
kind: Secret
metadata:
  name: customer-p1-app
  namespace: argocd

---
