kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - namespace.yaml
  - secret.yaml 

patches:
  - target:
      kind: Secret
      name: newrelic-license-key
    patch: |
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: Skip

  - target:
      kind: Namespace
      name: newrelic
    patch: |
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: Skip
