# original port is 8080
# that port is turned off as the main pipeline forwards logs to opensearch
# 8081 is used by the s3 bucket pipeline
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logstash-elastic
  namespace: elastic-stack-logging
spec:
  template:
    spec:
      containers:
      - name: logstash
        readinessProbe:
          httpGet:
            port: 8081
        startupProbe:
          httpGet:
            port: 8081

---