# ConfigMap to overwrite the container image pipelines.yml 
# config in order to disable the main(opensearch) pipeline.
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline-config
  namespace: elastic-stack-logging
data:
  # pipelines.yml: |
  #   - pipeline.id: customer
  #     path.config: "/usr/share/logstash/pipeline/customer"
  #   - pipeline.id: s3
  #     path.config: "/usr/share/logstash/pipeline/s3"
  #   - pipeline.id: dlq
  #     path.config: "/usr/share/logstash/pipeline/dlq"
  #     pipeline.workers: 1
  02-input-filters.conf: |-
    filter {
      # Drop all events
      drop {}
    }
    output {}  
---

# original port is 8080
# that port is turned off as the main pipeline forwards logs to opensearch
# 8081 is used by the s3 bucket pipeline
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logstash-elastic
  namespace: elastic-stack-logging
spec:
  template:
    spec:
      containers:
      - name: logstash
        readinessProbe:
          httpGet:
            port: 8081
        startupProbe:
          httpGet:
            port: 8081
        volumeMounts:
        # - name: logstash-pipelines
        #   mountPath: /usr/share/logstash/config/pipelines.yml
        #   subPath: pipelines.yml
        - name: logstash-input-filters
          mountPath: /usr/share/logstash/pipeline/main/02-input-filters.conf
          subPath: 02-input-filters.conf
        - name: empty-file
          mountPath: /usr/share/logstash/pipeline/main/
      volumes:
      # - name: logstash-pipelines
      #   configMap:
      #     name: logstash-pipeline-config
      #     items:
      #     - key: pipelines.yml
      #       path: pipelines.yml 
      - name: logstash-input-filters
        configMap:
          name: logstash-pipeline-config
          items:
          - key: 02-input-filters.conf
            path: 02-input-filters.conf
      - name: empty-file
        emptyDir: {}            
