apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-agent
  namespace: prometheus
spec:
  template:
    spec:
      volumes:
        - name: os-creds
          $patch: delete
      volumeMounts:
        - name: os-creds
          $patch: delete
