kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: argocd

resources:
  - base
  - argocd-image-updater.yaml
  - custom-resources.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: install-custom-tools
    files:
      - install-custom-tools.sh

# Point to the ping-cluster-tools repo equivalents pushed to ECR
# images:
#   # - name: quay.io/argoproj/argocd
#   #   newName: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/argo/argocd
#   # - name: redis
#   #   newName: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/redis
#   # - name: ghcr.io/dexidp/dex
#   #   newName: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/dexidp/dex

patches:
  - path: argo-notifications-cm.yaml

patchesStrategicMerge:
  # Set the several log values to "warn"
  - |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: argocd-cmd-params-cm
    data:
      # Set the logging level. One of: debug|info|warn|error (default "info")
      controller.log.level: "warn"
      server.log.level: "warn"
      reposerver.log.level: "warn"

  # Add git-ops-command.sh as the config management tool to build the uber Kubernetes YAML
  # TODO: update the configManagementPlugins to run via a Sidecar - this won't happen until at least Argo 2.6
  # NOTE: This shouldn't be necessary since we will remove git-ops-command.sh as part of breaking down the monorepo
  # -> Issue: https://github.com/argoproj/argo-cd/issues/8117
  # Ignore diffs in webhook client CA bundle (ref: https://argo-cd-docs.readthedocs.io/en/latest/user-guide/diffing/)
  - |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: argocd-cm
    data:
      accounts.image-updater: apiKey
      accounts.config-team: apiKey,login
      configManagementPlugins: |
        - name: git-ops-command
          generate:
            command: [ "git-ops-command.sh" ]
      resource.customizations: |
        admissionregistration.k8s.io/MutatingWebhookConfiguration:
          ignoreDifferences: |
            jsonPointers:
            - /webhooks/0/clientConfig/caBundle
      kustomize.buildOptions: --load-restrictor LoadRestrictionsNone --enable-helm

  # Policy for a user 'config-team` to allow restart on K8s StatefulSets
  - |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: argocd-rbac-cm
    data:
      policy.csv: |
        p, config-team, applications, action/apps/StatefulSet/restart, *, allow
      policy.default: role:readonly

  # Mount Beluga-specific scripts within the container
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: argocd-repo-server
    spec:
      template:
        spec:
          containers:
          - name: argocd-repo-server
            volumeMounts:
              - name: git-ops-command
                mountPath: /usr/local/bin/git-ops-command.sh
                subPath: git-ops-command.sh
              - name: tools-dir
                mountPath: /usr/local/bin/envsubst
                subPath: envsubst
              - name: tools-dir
                mountPath: /usr/local/bin/kustomize
                subPath: kustomize
              - name: tools-dir
                mountPath: /usr/local/bin/git-remote-codecommit
                subPath: git-remote-codecommit
              - name: tools-dir
                mountPath: /home/argocd/.local/lib/python3.7/site-packages/git_remote_codecommit/__init__.py
                subPath: __init__.py

  # Add an init container to install a few custom tools into the ArgoCD repo server
  # TODO: try to manage this image in a way that isn't inline to aid with upgrading/finding the image
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: argocd-repo-server
    spec:
      template:
        spec:
          initContainers:
          # Installs custom tools
          - name: install-custom-tools
            image: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/python:3.9.1-slim
            command: [ "install-custom-tools.sh" ]
            volumeMounts:
            - name: tools-dir
              mountPath: /tools
            - name: install-custom-tools
              mountPath: /usr/local/bin/install-custom-tools.sh
              subPath: install-custom-tools.sh

  # Add Beluga-specific volumes to the pod
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: argocd-repo-server
    spec:
      template:
        spec:
          volumes:
          - name: tools-dir
            emptyDir: {}
          - name: git-ops-command
            configMap:
              name: git-ops-command
              defaultMode: 0555
          - name: install-custom-tools
            configMap:
              name: install-custom-tools
              defaultMode: 0555

  # Add the "sealedsecrets.bitnami.com/managed: true" annotation to secrets so they are manageable by Bitnami
  - |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: argocd-notifications-secret
      annotations:
        sealedsecrets.bitnami.com/managed: "true"

  - |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: argocd-secret
      annotations:
        sealedsecrets.bitnami.com/managed: "true"

  # Add init container to create Argo clusters for all CDEs from customer-hub
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: argocd-server
    spec:
      template:
        spec:
          initContainers:
          - name: argocd-bootstrap
            image: public.ecr.aws/r2h3l6e4/pingcloud-services/argocd-bootstrap/dev:v1.18-release-branch-latest
            imagePullPolicy: Always
            envFrom:
              - configMapRef:
                  name: argocd-bootstrap
