apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter-config
  namespace: prometheus
data:
  config.yml: |
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          valid_status_codes: [200, 201]
          method: GET