kind: Service
apiVersion: v1
metadata:
  name: blackbox-exporter
  namespace: prometheus
spec:
  selector:
    app: blackbox
  ports:
  - port: 9115
    targetPort: 9115
    name: http
  clusterIP: None