kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../../../base/karpenter

patchesJson6902:

# TODO: Patch the limits to prevent Karpenter from provisioning resources beyond the expected amount.

# Adjust the volume size for instances that will be provisioned by Karpenter.
patches:
  - target:
      kind: EC2NodeClass
      name: default
    patch: |-
      - op: replace
        path: /spec/blockDeviceMappings/0/ebs/volumeSize
        value: '120Gi'
  - target:
      kind: EC2NodeClass
      name: pd-only
    patch: |-
      - op: replace
        path: /spec/blockDeviceMappings/0/ebs/volumeSize
        value: '120Gi'
  - target:
      kind: EC2NodeClass
      name: pgo-only
    patch: |-
      - op: replace
        path: /spec/blockDeviceMappings/0/ebs/volumeSize
        value: '120Gi'

patchesStrategicMerge:
- |-
  apiVersion: karpenter.sh/v1beta1
  kind: NodePool
  metadata:
    name: default
  spec:
    template:
      spec:
        requirements:
          - key: "karpenter.k8s.aws/instance-category"
            operator: In
            values: ["c"]
          - key: "kubernetes.io/arch"
            operator: In
            values: ["arm64"]
          - key: "karpenter.sh/capacity-type"
            operator: In
            values: ["on-demand"]
          - key: kubernetes.io/os
            operator: In
            values: ["linux"]
          - key: "karpenter.k8s.aws/instance-generation"
            operator: In
            values: ["7"]

- |-
  apiVersion: karpenter.sh/v1beta1
  kind: NodePool
  metadata:
    name: pd-only
  spec:
    template:
      spec:
        requirements:
          - key: "karpenter.k8s.aws/instance-category"
            operator: In
            values: ["r"]
          - key: "kubernetes.io/arch"
            operator: In
            values: ["arm64"]
          - key: "karpenter.sh/capacity-type"
            operator: In
            values: ["on-demand"]
          - key: kubernetes.io/os
            operator: In
            values: ["linux"]
          - key: "karpenter.k8s.aws/instance-generation"
            operator: In
            values: ["7"]

- |-
  apiVersion: karpenter.sh/v1beta1
  kind: NodePool
  metadata:
    name: pgo-only
  spec:
    template:
      spec:
        requirements:
          - key: "karpenter.k8s.aws/instance-category"
            operator: In
            values: ["c"]
          - key: "kubernetes.io/arch"
            operator: In
            values: ["amd64"]
          - key: "karpenter.sh/capacity-type"
            operator: In
            values: ["on-demand"]
          - key: kubernetes.io/os
            operator: In
            values: ["linux"]
          - key: "karpenter.k8s.aws/instance-generation"
            operator: In
            values: ["7"]