apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesJson6902:
  - target:
      version: v1
      kind: CustomResourceDefinition
      name: grafanas.grafana.integreatly.org
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "ServerSideApply=true"

  - target:
      version: v1
      kind: CustomResourceDefinition
      name: grafanadashboards.grafana.integreatly.org
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "ServerSideApply=true"

  - target:
      version: v1
      kind: CustomResourceDefinition
      name: grafanadatasources.grafana.integreatly.org
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "ServerSideApply=true"

  - target:
      version: v1
      kind: CustomResourceDefinition
      name: grafanafolders.grafana.integreatly.org
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "ServerSideApply=true"
