kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- storage.yaml
- logstash.yaml
- hpa.yaml
- unused-pv-cleanup.yaml
- secret.yaml
- pdb.yaml
- customer_pipelines


configMapGenerator:
- name: logstash-pipeline-main
  files:
    - 10-kube-proxy-filters.conf