---

### Ping app SSH private key ###

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ssh-id-key-secret
data:
  id_rsa: |
    ${SSH_ID_KEY_BASE64}

---

# ---
# ### Optional certificate(s) to add to the PingDataSync truststore ###
# ### Note: This should only be for servers outside P1AS that you are trying to sync with. ###
# ###       The secret key can be anything such as 'external-server-public-certificate' ###
# apiVersion: v1
# kind: Secret
# type: Opaque
# metadata:
#  name: pingdatasync-truststore-certs
# data:
#  external-server-public-certificate: |
#    <base64 encoding of external server public certificate>

---

# Add pingaccess.lic (case-sensitive) to the data section with the base64-encoded value of the license file
apiVersion: v1
kind: Secret
metadata:
  name: pingaccess-license
type: Opaque

---

# Add pingaccess.lic (case-sensitive) to the data section with the base64-encoded value of the license file
apiVersion: v1
kind: Secret
metadata:
  name: pingaccess-was-license
type: Opaque

---

### Product passwords ###

# Supported keys:
# Exported as environment variables: PF_ADMIN_USER_PASSWORD, PF_LDAP_PASSWORD, DA_OAUTH_TOKEN_VALIDATOR_SECRET, PC_ADMIN_USER_PASSWORD
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingcommon-passwords

---

# Supported keys:
# Mounted as file: root-user-password
# Exported as environment variable: ROOT_USER_PASSWORD, EXT_PD_SYNC_BIND_DN_PASSWORD, EXT_PD_ADMIN_BIND_DN_PASSWORD
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingdatasync-passwords

---

# Supported keys:
# Exported as environment variables: PA_ADMIN_USER_PASSWORD, OLD_PA_ADMIN_USER_PASSWORD
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingaccess-passwords

---

# Supported keys:
# Exported as environment variables: PA_ADMIN_USER_PASSWORD, OLD_PA_ADMIN_USER_PASSWORD,
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingaccess-was-passwords

---

# Supported keys:
# Exported as environment variables: HEALTHCHECK_USER_NAME, HEALTHCHECK_USER_PASSWORD
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: healthcheck-user
  namespace: health

---

# Logstash password to send logs to the opensearch
apiVersion: v1
kind: Secret
metadata:
  name: os-logstash-creds
  namespace: elastic-stack-logging

---
# NOTE: This file must always end with `---` so that argo secrets can be appended correctly for dev cluster deployments
