kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ${K8S_GIT_URL}/k8s-configs/cluster-tools/${KUSTOMIZE_BASE}/ingress/nginx/public?ref=${K8S_GIT_BRANCH}

configMapGenerator:
- name: ingress-bootstrap-environment-variables
  behavior: merge
  literals:
    - SSM_PATH_DHPARAM=/pcpt/beluga/ingress-keys/ingress-nginx-public
    - REGION=${REGION}

patchesStrategicMerge:

### Assign Elastic IP addresses to the ingress-nginx-public Network Load Balancer by adding the annotation ###
# - |-
#   apiVersion: v1
#   kind: Service
#   metadata:
#     name: ingress-nginx
#     namespace: ingress-nginx-public
#     annotations:
#       service.beta.kubernetes.io/aws-load-balancer-type: nlb
#       ${NLB_NGX_PUBLIC_ANNOTATION_KEY_VALUE}

### Ingress service account ###
# - |-
#   apiVersion: v1
#   kind: ServiceAccount
#   metadata:
#     name: nginx-ingress-serviceaccount
#     annotations:
#       ${IRSA_INGRESS_ANNOTATION_KEY_VALUE}

patchesJson6902:

# - target:
#     group: apps
#     version: v1
#     kind: Deployment
#     name: nginx-ingress-controller
#     namespace: ingress-nginx-public
#   patch: |-
#     - op: add
#       path: /spec/template/spec/containers/0/args/-
#       value:
#         --default-ssl-certificate=${PING_CLOUD_NAMESPACE}/acme-tls-cert

### Patch to inject environment variables to SigSci agent container ###
# - target:
#     group: apps
#     version: v1
#     kind: Deployment
#     name: nginx-ingress-controller
#     namespace: ingress-nginx-public
#   patch: |-
#     - op: replace
#       path: /spec/template/spec/containers/1/env/0/value
#       value: ${REGION}

#     - op: replace
#       path: /spec/template/spec/containers/1/env/1/value
#       value: ${ENVIRONMENT_PREFIX}
